// frontend/src/components/widgets/SliderWidget.tsx
import { createSignal, onMount, onCleanup, Show } from "solid-js";

interface SliderImage {
  id: string;
  url: string;
  alt?: string;
  index: number;
}

interface SliderConfig {
  slideDuration: number;
  transitionDuration: number;
  transitionType: "fade" | "slide" | "slide-up" | "zoom" | "flip";
  fitMode: "contain" | "cover" | "fill";
  backgroundColor: string;
  images?: SliderImage[];
}

interface SliderWidgetProps {
  config: SliderConfig;
}

export default function SliderWidget(props: SliderWidgetProps) {
  const [currentSlideIndex, setCurrentSlideIndex] = createSignal(0);

  const slides = () => props.config.images || [];
  const currentSlide = () => {
    const slideList = slides();
    if (slideList.length === 0) return null;
    return slideList[currentSlideIndex() % slideList.length];
  };

  const slideDuration = () => Math.max(1000, (props.config.slideDuration || 5) * 1000);
  const transitionDuration = () => Math.max(200, Math.min(2000, props.config.transitionDuration || 500));

  const getImageStyle = () => {
    const fitMode = props.config.fitMode || "contain";

    switch (fitMode) {
      case "cover":
        return {
          width: "100%",
          height: "100%",
          objectFit: "cover" as const,
        };
      case "fill":
        return {
          width: "100%",
          height: "100%",
          objectFit: "fill" as const,
        };
      case "contain":
      default:
        return {
          maxWidth: "100%",
          maxHeight: "100%",
          objectFit: "contain" as const,
        };
    }
  };

  const nextSlide = () => {
    const slideList = slides();
    if (slideList.length <= 1) return;
    setCurrentSlideIndex((prev) => (prev + 1) % slideList.length);
  };

  onMount(() => {
    if (slides().length > 1) {
      const interval = setInterval(nextSlide, slideDuration());
      onCleanup(() => clearInterval(interval));
    }
  });

  return (
    <div
      style={{
        "background-color": props.config.backgroundColor || "transparent",
        width: "100%",
        height: "100%",
        position: "relative",
        overflow: "hidden",
      }}
    >
      <Show
        when={slides().length > 0}
        fallback={
          <div style={{ color: "white", "text-align": "center", padding: "20px" }}>
            <p>No images available for slider</p>
            <p style={{ "font-size": "0.8em", opacity: "0.7" }}>Upload images or wait for demo images to load</p>
          </div>
        }
      >
        <div
          style={{
            width: "100%",
            height: "100%",
            position: "relative",
          }}
        >
          <Show when={currentSlide()}>
            {(slide) => (
              <div
                class={`slide-transition slide-${props.config.transitionType}`}
                style={{
                  position: "absolute",
                  top: "0",
                  left: "0",
                  width: "100%",
                  height: "100%",
                  display: "flex",
                  "align-items": "center",
                  "justify-content": "center",
                  "--transition-duration": `${transitionDuration()}ms`,
                }}
              >
                <img
                  src={slide().url}
                  alt={slide().alt || `Slide ${slide().index + 1}`}
                  style={{
                    ...getImageStyle(),
                    borderRadius: "4px",
                  }}
                />
              </div>
            )}
          </Show>
        </div>
      </Show>

      <style>{`
        .slide-transition {
          animation: slideIn var(--transition-duration, 500ms) ease-in-out;
        }

        .slide-fade {
          animation: fadeIn var(--transition-duration, 500ms) ease-in-out;
        }

        .slide-slide {
          animation: slideInFromRight var(--transition-duration, 500ms) ease-in-out;
        }

        .slide-slide-up {
          animation: slideInFromBottom var(--transition-duration, 500ms) ease-in-out;
        }

        .slide-zoom {
          animation: zoomIn var(--transition-duration, 500ms) ease-in-out;
        }

        .slide-flip {
          animation: flipIn var(--transition-duration, 500ms) ease-in-out;
        }

        @keyframes fadeIn {
          from {
            opacity: 0;
          }
          to {
            opacity: 1;
          }
        }

        @keyframes slideInFromRight {
          from {
            transform: translateX(100%);
            opacity: 0;
          }
          to {
            transform: translateX(0);
            opacity: 1;
          }
        }

        @keyframes slideInFromBottom {
          from {
            transform: translateY(100%);
            opacity: 0;
          }
          to {
            transform: translateY(0);
            opacity: 1;
          }
        }

        @keyframes zoomIn {
          from {
            opacity: 0;
            transform: scale(0.8);
          }
          to {
            opacity: 1;
            transform: scale(1);
          }
        }

        @keyframes flipIn {
          from {
            transform: rotateY(90deg);
            opacity: 0;
          }
          to {
            transform: rotateY(0);
            opacity: 1;
          }
        }
      `}</style>
    </div>
  );
}

// assets/vue/SliderWidget.vue
<template>
  <div class="slider-widget" :style="containerStyle">
    <div v-if="slides.length === 0" class="no-slides-message" style="color: white; text-align: center; padding: 20px;">
      <p>No images available for slider</p>
      <p style="font-size: 0.8em; opacity: 0.7;">Upload images or wait for demo images to load</p>
    </div>
    <div v-else class="slide-container" :style="slideContainerStyle">
      <transition
        :name="transitionType"
        :duration="{ enter: transitionDuration, leave: transitionDuration }"
        mode="out-in"
      >
        <div v-if="currentSlide" :key="currentSlide.id" class="slide" :style="slideStyle">
          <img
            :src="currentSlide.url"
            :alt="currentSlide.alt || `Slide ${currentSlide.index + 1}`"
            class="slide-image"
            :style="imageStyle"
            @load="handleImageLoad"
            @error="handleImageError"
          />
        </div>
      </transition>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted, onUnmounted } from 'vue'

interface SliderImage {
  id: string
  url: string
  alt?: string
  index: number
}

interface SliderConfig {
  slide_duration: number
  transition_duration: number
  transition_type: string
  fit_mode: string
  background_color: string
  images?: SliderImage[]
}

interface SliderEvent {
  id: string
  type: string
  images?: SliderImage[]
  timestamp: Date
}

const props = defineProps<{
  config: SliderConfig
  event?: SliderEvent
}>()

const currentSlideIndex = ref(0)
const isTransitioning = ref(false)
const intervalId = ref<ReturnType<typeof setInterval> | null>(null)

const slides = computed(() => {
  const eventImages = props.event?.images
  const configImages = props.config.images
  const result = eventImages || configImages || []

  // Debug logging
  console.log('[SliderWidget] Computing slides:', {
    eventImages,
    configImages,
    resultCount: result.length,
    result
  })

  return result
})

const currentSlide = computed(() => {
  if (slides.value.length === 0) return null
  return slides.value[currentSlideIndex.value % slides.value.length]
})

const slideDuration = computed(() => {
  return Math.max(1000, (props.config.slide_duration || 5) * 1000)
})

const transitionDuration = computed(() => {
  return Math.max(200, Math.min(2000, (props.config.transition_duration || 500)))
})

const transitionType = computed(() => {
  return props.config.transition_type || 'fade'
})

const containerStyle = computed(() => ({
  backgroundColor: props.config.background_color || 'transparent',
  width: '100%',
  height: '100%',
  position: 'relative',
  overflow: 'hidden'
}))

const slideContainerStyle = computed(() => ({
  width: '100%',
  height: '100%',
  position: 'relative'
}))

const slideStyle = computed(() => ({
  position: 'absolute',
  top: '0',
  left: '0',
  width: '100%',
  height: '100%',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center'
}))

const imageStyle = computed(() => {
  const fitMode = props.config.fit_mode || 'contain'

  switch (fitMode) {
    case 'cover':
      return {
        width: '100%',
        height: '100%',
        objectFit: 'cover' as const
      }
    case 'fill':
      return {
        width: '100%',
        height: '100%',
        objectFit: 'fill' as const
      }
    case 'contain':
    default:
      return {
        maxWidth: '100%',
        maxHeight: '100%',
        objectFit: 'contain' as const
      }
  }
})

const nextSlide = () => {
  if (slides.value.length <= 1) return

  isTransitioning.value = true
  currentSlideIndex.value = (currentSlideIndex.value + 1) % slides.value.length

  setTimeout(() => {
    isTransitioning.value = false
  }, transitionDuration.value)
}

const startSlideshow = () => {
  if (intervalId.value) {
    clearInterval(intervalId.value)
  }

  if (slides.value.length > 1) {
    intervalId.value = setInterval(nextSlide, slideDuration.value)
  }
}

const stopSlideshow = () => {
  if (intervalId.value) {
    clearInterval(intervalId.value)
    intervalId.value = null
  }
}

const handleImageLoad = () => {
  // Image loaded successfully
}

const handleImageError = () => {
  console.warn('Failed to load slide image:', currentSlide.value?.url)
}

// Watch for config changes to restart slideshow
watch([() => props.config.slide_duration, () => slides.value], () => {
  startSlideshow()
}, { deep: true })

// Watch for event changes (new images uploaded)
watch(() => props.event, (newEvent) => {
  if (newEvent?.images && newEvent.images.length > 0) {
    currentSlideIndex.value = 0
    startSlideshow()
  }
}, { deep: true })

onMounted(() => {
  console.log('[SliderWidget] Mounted with:', {
    config: props.config,
    event: props.event,
    slidesCount: slides.value.length,
    slides: slides.value
  })

  if (slides.value.length > 0) {
    startSlideshow()
  }
})

onUnmounted(() => {
  stopSlideshow()
})
</script>

<style scoped>
.slider-widget {
  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
}

.slide-container {
  position: relative;
}

.slide-image {
  border-radius: 4px;
}

/* Fade transition */
.fade-enter-active,
.fade-leave-active {
  transition: opacity var(--transition-duration, 500ms) ease-in-out;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}

/* Slide transition */
.slide-enter-active,
.slide-leave-active {
  transition: transform var(--transition-duration, 500ms) ease-in-out;
}

.slide-enter-from {
  transform: translateX(100%);
}

.slide-leave-to {
  transform: translateX(-100%);
}

/* Slide up transition */
.slide-up-enter-active,
.slide-up-leave-active {
  transition: transform var(--transition-duration, 500ms) ease-in-out;
}

.slide-up-enter-from {
  transform: translateY(100%);
}

.slide-up-leave-to {
  transform: translateY(-100%);
}

/* Zoom transition */
.zoom-enter-active,
.zoom-leave-active {
  transition: all var(--transition-duration, 500ms) ease-in-out;
}

.zoom-enter-from,
.zoom-leave-to {
  opacity: 0;
  transform: scale(0.8);
}

/* Flip transition */
.flip-enter-active,
.flip-leave-active {
  transition: transform var(--transition-duration, 500ms) ease-in-out;
}

.flip-enter-from {
  transform: rotateY(90deg);
}

.flip-leave-to {
  transform: rotateY(-90deg);
}
</style>
